// 12-Factor: no runtime toggle. Environment is determined at build time
// via --dart-define. See lib/src/providers/core_providers.dart.
//
// Usage:
//   local:   flutter run --dart-define=API_URL=http://127.0.0.1:8000
//   staging: flutter build web --dart-define=API_URL=https://inea-scents-staging.onrender.com
//   prod:    flutter build web --dart-define=API_URL=https://inea-scents.onrender.com
//
// Do NOT edit this file to switch backends. Pass the flag at build time.
// Vercel Preview env uses staging URL; Vercel Production uses prod URL.
enum Environment { local, staging, production }

// Deprecated: use --dart-define=API_URL instead. Will be removed.
@Deprecated('Use --dart-define=API_URL. Will be removed in next version.')
const Environment currentEnvironment = Environment.local;
