// 12-Factor: no runtime toggle. Environment is determined at build time
// via --dart-define. See lib/src/providers/core_providers.dart.
//
// Usage:
//   local:   flutter run --dart-define=API_URL=http://127.0.0.1:8000
//   prod:    flutter build web --dart-define=API_URL=https://inea-scents.onrender.com
//
// Do NOT edit this file to switch backends. Pass the flag at build time.
// Only prod exists in the cloud; Vercel Preview and Production use the prod URL.
// See backend docs/adr/0009-two-environments.md.
enum Environment { local, production }

// Deprecated: use --dart-define=API_URL instead. Will be removed.
@Deprecated('Use --dart-define=API_URL. Will be removed in next version.')
const Environment currentEnvironment = Environment.local;